### ISSUE TITLE
Rename to modify-keys

### ISSUE THREAD

**Issue by yuchi** [sindresorhus/modify-values#1]
Or use `Object.getOwnPropertyNames` instead of `Object.keys`.

IMHO.

**Comment by sindresorhus** [comment]
Huh? This modifies the values of an object. Are you sure you opened this on the right repo?

**Comment by yuchi** [comment]
Sorry, modify-keys-values

**Comment by sindresorhus** [comment]
Yeah, but why? I don't get your reasoning.

**Comment by yuchi** [comment]
IMHO the name doesn't convey the fact that your not iterating over all the properties, only enumerate ones. My proposals are lame, I have to admit.

**Comment by sindresorhus** [comment]
Well, neither does `Object.keys`. Iterating over enumerable properties is the default. Object.keys does it. Object.assign does it. This does it. It shouldn't be a surprise.

**Comment by yuchi** [comment]
Gotcha! Sorry for wasting you time! (Btw, I didn't know about object.assign iterating enumerable props only, this makes a lot of sense now)
